name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *' # اجرا هر روز
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Snake animation
        uses: "Platane/snk@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          branch: output
